services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Harmony\Bundle\ExtensionBundle\Command\AssetsInstallCommand: ~

    Harmony\Bundle\ExtensionBundle\Manager\ComponentManager: ~